# Generated by Django 4.2 on 2023-04-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, null=True)),
                ('url_site', models.URLField(max_length=500, null=True)),
                ('signup_method', models.CharField(choices=[('faceboook', 'facebook'), ('instagram', 'instagram'), ('google', 'google'), ('email', 'email'), ('github', 'github')], max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
